# Universal Functions (ufuncs) in NumPy

    A universal function (ufunc) in NumPy is a function that performs element-wise operations on ndarray objects.

    You can think of ufuncs as fast, vectorized wrappers for simple scalar functions.

    They:
    Operate element-wise
    Avoid explicit Python loops
    Are implemented in optimized C code
    Are much faster than pure Python loops

In [1]:
import numpy as np

In [2]:
arr = np.array([-12, -4, 4, 2, 0])
np.sqrt(arr) # [nan, nan, 2., 1.41421356, 0.]
np.exp(arr)

/tmp/ipykernel_37505/1317354238.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr) # [nan, nan, 2., 1.41421356, 0.]


array([6.14421235e-06, 1.83156389e-02, 5.45981500e+01, 7.38905610e+00,
       1.00000000e+00])

In [3]:
x = np.array([1.2, 2.8, 5, 12.1])
y = np.array([5.0, 2.1, 0, 8.5])

np.maximum(x, y) # array([ 5. ,  2.8,  5. , 12.1])

remainder, whole_part = np.modf(y)
remainder # [0.  0.1 0.  0.5]
whole_part # [5. 2. 0. 8.]


array([5., 2., 0., 8.])

### NumPy Mathematical Functions Cheat Sheet

### **Basic Mathematical Functions**
| Function | Description | Example | Output |
|----------|-------------|---------|--------|
|`np.abs(arr)` | Absolute value for int, float, complex |	`np.abs([-1, -2.5])`	|[1. , 2.5] |
`np.fabs(arr)` |	Absolute value for floats only | `np.fabs([-1.5, -2.5])` | [1.5, 2.5] |
`np.sqrt(arr)` |	Square root of each element |	`np.sqrt([4, 9])`	| [2., 3.] |
`np.square(arr)`	| Square of each element |	`np.square([2, 3])` |	[4, 9] |
`np.exp(arr)` |	Exponential e^x	| `np.exp([0, 1])` |	[1., 2.718] |

### **Logarithmic Functions**
| Function | Description | Example | Output |
|----------|-------------|---------|--------|
`np.log(arr)` |	Natural logarithm (base e)	| `np.log([1, 10])` |	[0., 2.302] |
`np.log10(arr)` |	Base-10 logarithm |	`np.log10([1, 100])` |	[0., 2.] |
`np.log2(arr)` |	Base-2 logarithm |	`np.log2([1, 8])`	| [0., 3.] |
`np.log1p(arr)` |	log(1 + x) for small x	| `np.log1p(0.001)` |	0.0009995 |

### **Rounding & Sign Functions**
| Function | Description | Example | Output |
|----------|-------------|---------|--------|
`np.sign(arr)` |	Sign: 1(positive), 0(zero), -1(negative) |	`np.sign([-5, 0, 5])`	| [-1., 0., 1.] |
`np.ceil(arr)` |	Smallest integer ≥ element |	`np.ceil([1.2, -1.8])` |	[ 2., -1.] |
`np.floor(arr)` |	Largest integer ≤ element |	`np.floor([1.2, -1.8])` |	[ 1., -2.]
`np.rint(arr)` |	Round to nearest integer |	`np.rint([1.2, 2.7])` |	[1., 3.]
`np.modf(arr)` |	Return fractional & integer parts |	`np.modf([1.2, 2.7])` |	([0.2, 0.7], [1., 2.]) |

### **Special Value Checks**
| Function | Description | Example | Output |
|----------|-------------|---------|--------|
`np.isnan(arr)` |	Check for NaN values |	`np.isnan([1, np.nan])` |	[False, True] |
`np.isfinite(arr)` |	Check for finite values |	`np.isfinite([1, np.inf])` |	[True, False] |
`np.isinf(arr)` |	Check for infinite values |	`np.isinf([1, np.inf])` |	[False, True] |

### **Trigonometric Functions**
| Function | Description | Example | Output |
|----------|-------------|---------|--------|
`np.sin(arr)` |	Sine function |	`np.sin([0, π/2])` |	[0., 1.] |
`np.cos(arr)` |	Cosine function |	`np.cos([0, π])` |	[1., -1.] |
`np.tan(arr)` |	Tangent function |	`np.tan([0, π/4])` |	[0., 1.] |
`np.arcsin(arr)` |	Inverse sine |	`np.arcsin([0, 1])` |	[0., 1.571] |
`np.arccos(arr)` |	Inverse cosine |	`np.arccos([0, 1])` |	[1.571, 0.] |
`np.arctan(arr)`|	Inverse tangent |	`np.arctan([0, 1])` |	[0., 0.785] |

### **Hyperbolic Functions**
| Function | Description | Example | Output |
|----------|-------------|---------|--------|
`np.sinh(arr)` |	Hyperbolic sine|	`np.sinh([0, 1])`|	[0., 1.175] |
`np.cosh(arr)`|	Hyperbolic cosine	|`np.cosh([0, 1])`|[1., 1.543]|
`np.tanh(arr)`|	Hyperbolic tangent	|`np.tanh([0, 1])`	|[0., 0.762]|

### **Logical Operations**
| Function | Description | Example | Output |
|----------|-------------|---------|--------|
`np.logical_not(arr)`	| Logical NOT (equivalent to ~arr)|`	np.logical_not([True, False])`|	[False, True]|

#### Key Notes:

    All functions operate element-wise on arrays
    Most functions preserve the dtype of the input
    Use` np.nan` , `np.inf`, `-np.inf `for special values
    Trigonometric functions use radians, not degrees
    For degree conversion: `np.radians(degrees)` or `np.degrees(radians)`


## NumPy Array Operations Cheat Sheet

### **Basic Arithmetic Operations**
| Function | Description | Equivalent Operator | Example | Output |
|----------|-------------|---------------------|---------|--------|
`np.add(x, y)`|	Add corresponding elements|	x + y	|`np.add([1,2], [3,4])`	|[4, 6]
`np.subtract(x, y)`|	Subtract y from x |	x - y	|`np.subtract([5,6], [2,1])	`|[3, 5]
`np.multiply(x, y)`|	Multiply elements|	x * y|	`np.multiply([2,3], [4,5])`	|[8, 15]
`np.divide(x, y)`|	Divide elements	|x / y|`	np.divide([10,20], [2,5])`	|[5., 4.]
`np.floor_divide(x, y)`|	Floor division	|x // y	|`np.floor_divide([10,20], [3,6])`|	[3, 3]
`np.power(x, y)`|	x to the power of y	|x ** y	|`np.power([2,3], [2,3])`|	[4, 27]
`np.mod(x, y)`	|Remainder of division	|x % y	|`np.mod([10,20], [3,6])`|	[1, 2]

### **Comparison Operations**
| Function | Description | Equivalent Operator | Example | Output |
|----------|-------------|---------------------|---------|--------|
`np.maximum(x, y)`|	Element-wise maximum|	-	|`np.maximum([1,5], [4,2])`|	[4, 5]
`np.fmax(x, y)`|	Maximum ignoring NaN|	-|	`np.fmax([1,np.nan], [4,2])`|	[4., 2.]
`np.minimum(x, y)`|	Element-wise minimum|	-	|`np.minimum([1,5], [4,2])`|	[1, 2]
`np.fmin(x, y)`	|Minimum ignoring NaN	|-	|`np.fmin([1,np.nan], [4,2])`|	[1., 2.]
`np.greater(x, y)`|	Element-wise >|	x > y|	`np.greater([1,5], [4,2])`	|[False, True]
`np.greater_equal(x, y)`	|Element-wise ≥	|x >= y|	`np.greater_equal([1,5], [1,2])`	|[True, True]
`np.less(x, y)`	|Element-wise <|	x < y|	`np.less([1,5], [4,2])`|	[True, False]
`np.less_equal(x, y)`|	Element-wise ≤|	x <= y| `	np.less_equal([1,5], [1,2])`|	[True, False]
`np.equal(x, y)`	|Element-wise ==|	x == y|	`np.equal([1,5], [1,2])`|	[True, False]
`np.not_equal(x, y)`|	Element-wise !|x != y	|`np.not_equal([1,5], [1,2])`	|[False, True]

### **Sign & Logical Operations**
| Function | Description | Example | Output |
|----------|-------------|---------|--------|
`np.copysign(x, y)`|	Copy sign from y to x|	`np.copysign([-1,2], [1,-1])`|	[1., -2.]
`np.logical_and(x, y)`|	Logical AND|	`np.logical_and([T,T,F], [T,F,F])`|	[True, False, False]
`np.logical_or(x, y)`|	Logical OR|	`np.logical_or([T,T,F], [T,F,F])`|	[True, True, False]
`np.logical_xor(x, y)`|	Logical XOR	|`np.logical_xor([T,T,F], [T,F,F])`	|[False, True, False]

Key Features:

-    Element-wise operations: All functions operate element-by-element
-    Broadcasting: Functions support broadcasting between arrays of different shapes
-    NaN handling: `fmax` and `fmin` ignore NaN values while `maximum` and `minimum` propagate them
-    Type preservation: Operations preserve data types when possible
-    In-place operations: Most have in-place versions e.g., `np.add(x, y, out=x))`


#### Boardcasting Example

In [4]:
# Scalar with array
np.add([1, 2, 3], 5)        # [6, 7, 8]

# Array with different shapes
np.multiply([[1,2],[3,4]], [10, 20])  # [[10,40],[30,80]]

array([[10, 40],
       [30, 80]])

Performance Tips:

-    Use NumPy functions instead of Python loops for better performance
-    Functions with `f` prefix (fmax, fmin) are faster with NaN values
-    In-place operations save memory:` np.add(x, y, out=x)`


## Array-Oriented Programming


In [5]:
# the function sqrt(x^2 + y^2)

points = np.arange(-5, 5, 0.001) # # 1000 equally spaced points
xs , ys = np.meshgrid(points, points)
z = np.sqrt(xs**2, ys**2)

# An Example to understand meshgrid
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

xs2, ys2 = np.meshgrid(x, y)
xs2, ys2

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]]))

```python
# visualizations of this twodimensional array:
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 8))

# Heatmap
plt.subplot(2, 2, 1)
plt.imshow(z, cmap=plt.cm.viridis, extent=(-5, 5, -5, 5))
plt.colorbar(label='z value')
plt.title('Heatmap of sqrt(x² + y²)')

# contuor
plt.subplot(2, 2, 2)
contour = plt.contour(xs, ys, z, levels=20, cmap=plt.cm.plasma)
plt.clabel(contour, inline=True, fontsize=8)
plt.title('Contour plot')

# 3D
from mpl_toolkits.mplot3d import Axes3D
ax = plt.subplot(2, 2, 3, projection='3d')
surf = ax.plot_surface(xs, ys, z, cmap=plt.cm.coolwarm,
                      linewidth=0, antialiased=False)
plt.title('3D Surface')

# Distribution 
plt.subplot(2, 2, 4)
plt.hist(z.flatten(), bins=50, edgecolor='black')
plt.title('Distribution of z values')
plt.xlabel('z')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()
```

### Expressing Conditional Logic as Array Operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

result = np.where(cond, xarr, yarr) # x if condition else y
# [1.1, 2.2, 1.3, 1.4, 2.5]

# in python
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

### Mathematical and Statistical Methods

In [ ]:
# axis=0 : columns
# axis=1 : row

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr.mean(axis=1))  # [2, 5, 8]
print(arr.sum(axis=0))   # [12, 15, 18]

In [ ]:
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

print(arr.cumsum(axis=0))
# [[0, 1, 2],
#  [3, 5, 7],   # 0+3=3, 1+4=5, 2+5=7
#  [9, 12, 15]] # 3+6=9, 5+7=12, 7+8=15

print(arr.cumprod(axis=1))
# [[0, 0, 0],     # 0, 0*1=0, 0*1*2=0
#  [3, 12, 60],   # 3, 3*4=12, 12*5=60
#  [6, 42, 336]]  # 6, 6*7=42, 42*8=336

In [ ]:
# notice
zero = np.array([])
print(zero.sum()) # 0.0
print(np.mean(zero)) # nan

### **Boolean Arrays**
| Function | Description | Example |
|----------|-------------|---------|
sum()|	Count True values	|`(arr > 0).sum()`
any()|	Check if any element is True	|`arr.any()`
all()|	Check if all elements are True	|`arr.all()`

### **sorting**
| Function | Description | Example |
|----------|-------------|---------|
sort()|	In-place sort|	`arr.sort()`
np.sort()|	Return sorted copy|	`np.sort(arr)`
sort(axis)	| Sort along axis|	`arr.sort(axis=1)`

### **Set Operations**
| Function | Description | Example |
|----------|-------------|---------|
np.unique()	|Sorted unique values|	`np.unique(arr)`
np.in1d()|	Membership test|	`np.in1d(arr1, arr2)`
np.intersect1d()|	Common elements|	`np.intersect1d(arr1, arr2)`
np.union1d()	|Union of elements	| `np.union1d(arr1, arr2)`
np.setdiff1d()	|Set difference	| `np.setdiff1d(arr1, arr2)`
np.setxor1d()	|Symmetric difference	| `np.setxor1d(arr1, arr2)`

### **Statistical Methods**
| Function | Description | Example |
|----------|-------------|---------|
sum(), mean()	|Sum and mean	|`arr.sum(), arr.mean()`
std(), var()|	Standard deviation, variance|	`arr.std(), arr.var()`
min(), max()|	Minimum, maximum	|`arr.min(), arr.max()`
argmin(), argmax()|	Indices of min/max	|`arr.argmin(), arr.argmax()`
cumsum(), cumprod()|	Cumulative sum/product|	`arr.cumsum(), arr.cumprod()`

Key Features:
- Boolean Arrays: Use `.sum()` to count True values
- Sorting: `.sort()` modifies in-place, `np.sort()` returns copy
- Unique Values: `np.unique()` returns sorted unique elements
- Set Operations: NumPy has vectorized set operations for 1D arrays
- Axis Parameter: Many functions accept `axis` parameter for multi-dimensional arrays
- Vectorization: Always prefer NumPy's vectorized operations over Python loops for speed

    Remember: NumPy operations are optimized in C - much faster than Python loops!