# **NumPy**

In [1]:
import numpy as np

## Creating ndarrays

In [ ]:
# 1D array from list
data1 = [6, 7.5, 8, 10]
arr1 = np.array(data1)
print(type(arr1))    # <class 'numpy.ndarray'>
print(arr1.dtype)    # float64 (automatically inferred)

# 2D array from list of list
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2.ndim)     # 2 (dimensions)
print(arr2.shape)    # (2, 4) (rows, columns)
print(arr2.dtype)    # int64

In [ ]:
# zero array
zeros_arr = np.zeros(10) # [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
zeros_2d = np.zeros((3,2))

one_arr = np.ones((3, 2))
empty_arr = np.empty((2, 3)) # random array
# Never assume empty gives zeros!

full_arr = np.full((3, 2), 7)

# eye - (identity)
identity = np.eye(4)

## arange 

In [ ]:
# arange - NumPy version of range
arr = np.arange(10)
print(arr)  # [0 1 2 3 4 5 6 7 8 9]

arr = np.arange(5, 15)  # start, stop
print(arr)  # [5 6 7 8 9 10 11 12 13 14]

arr = np.arange(0, 20, 2)  # start, stop, step
print(arr)  # [0 2 4 6 8 10 12 14 16 18]

arr = np.arange(10, 0, -1)  # negative step
print(arr)  # [10 9 8 7 6 5 4 3 2 1]

## linspace 

In [ ]:
# linspace - equally spaced numbers
# 5 numbers between 0 and 1
arr = np.linspace(0, 1, 5)
print(arr)  # [0.   0.25 0.5  0.75 1.  ]

# 10 numbers between 0 and 2π
angles = np.linspace(0, 2*np.pi, 10)
print(angles)

## random array

In [ ]:
# Random numbers
# Uniform distribution [0, 1)
rand_arr = np.random.rand(3, 4)  # 3x4 array
print(rand_arr)

# Normal distribution (mean=0, std=1)
randn_arr = np.random.randn(3, 4)
print(randn_arr)

# Random integers
randint_arr = np.random.randint(0, 10, size=(3, 4))  # 0 to 9
print(randint_arr)

# Random seed for reproducibility
np.random.seed(42)  # Same random numbers every time
arr1 = np.random.rand(3)
print(arr1)

np.random.seed(42)  # Reset seed
arr2 = np.random.rand(3)
print(arr2)  # Same as arr1!

# otheer way to reset seed
rng = np.random.default_rng(42)
rng.random(3)

| Function | Description | Example |
|----------|-------------|---------|
| **array()** | Create from list/tuple | `np.array([1,2,3])` |
| **zeros()** | All zeros | `np.zeros((3,4))` |
| **ones()** | All ones | `np.ones((2,3))` |
| **empty()** | Uninitialized values | `np.empty((2,2))` |
| **full()** | Constant value | `np.full((3,3), 7)` |
| **arange()** | Similar to range | `np.arange(5,10)` |
| **linspace()** | Equal spacing | `np.linspace(0,1,5)` |
| **eye()** | Identity matrix | `np.eye(4)` |
| **random.rand()** | Uniform random | `np.random.rand(3,3)` |
| **random.randn()** | Normal random | `np.random.randn(3,3)` |

##  Arithmetic with NumPy Arrays

In [ ]:
# From the book example
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# [[1 2 3]
#  [4 5 6]]

# Multiplication
print(arr * arr)
# [[ 1  4  9]
#  [16 25 36]]

# Subtraction
print(arr - arr)
# [[0 0 0]
#  [0 0 0]]

# Division
print(1 / arr)
# [[1.         0.5        0.33333333]
#  [0.25       0.2        0.16666667]]

# Power
print(arr ** 2)
# [[ 1  4  9]
#  [16 25 36]]

# Square root
print(np.sqrt(arr))
# [[1.         1.41421356 1.73205081]
#  [2.         2.23606798 2.44948974]]

In [ ]:
# Scalar operations propagate
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Add scalar
print(arr + 10)
# [[11 12 13]
#  [14 15 16]]

# Multiply by scalar
print(arr * 2)
# [[ 2  4  6]
#  [ 8 10 12]]

# Comparison with scalar
print(arr > 3)
# [[False False False]
#  [ True  True  True]]

# Different operations
print(arr + 1.5)
# [[2.5 3.5 4.5]
#  [5.5 6.5 7.5]]

## ufunc (universal function)

In [ ]:
# From the book - unary ufuncs
arr = np.arange(10)
print(arr)  # [0 1 2 3 4 5 6 7 8 9]

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Binary ufuncs
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)

# Element-wise maximum
print(np.maximum(x, y))

# modf - fractional and integer parts
arr = np.random.randn(7) * 5
remainder, whole = np.modf(arr)
print(whole)
print(remainder)

### Comparisons

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr > 3) # [False False False  True]

# use for index
cond = arr !=3
print(arr[cond]) # [1 2 4]

### reshape and shape

In [ ]:
arr = np.arange(12)
print(arr.shape) # (12,)

# reshape to 2D
arr_2d = arr.reshape(3, 4)

# reshape to 3D
arr_3d = arr.reshape(2, 3, 2)  # 2 layers, 3 rows, 2 columns

# -1 means infer dimension
arr_reshaped = arr.reshape(4, -1)  # 4 rows, columns inferred

(12,)


### ndim, size, dytpe

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)      # 2 (dimensions)
print(arr.shape)     # (2, 3) (rows, columns)
print(arr.size)      # 6 (total elements)
print(arr.dtype)     # int64
print(arr.itemsize)  # 8 (bytes per element)
print(arr.nbytes)    # 48 (total bytes = size * itemsize)

### view vs copy

In [ ]:
# Views (no copy)
arr = np.arange(10)
view = arr[2:5]      # Slice creates a view
view[0] = 999
print(arr)           # [  0   1 999   3   4   5   6   7   8   9] (changed!)

# Copy explicitly
arr = np.arange(10)
copy = arr[2:5].copy()  # Force copy
copy[0] = 999
print(arr)           # [0 1 2 3 4 5 6 7 8 9] (unchanged!)

| Attribute | Description | Example |
|-----------|-------------|---------|
| **ndim** | Number of dimensions | `arr.ndim` |
| **shape** | Size of each dimension | `arr.shape` |
| **size** | Total number of elements | `arr.size` |
| **dtype** | Data type | `arr.dtype` |
| **itemsize** | Bytes per element | `arr.itemsize` |
| **nbytes** | Total bytes | `arr.nbytes` |
| **T** | Transpose | `arr.T` |
| **flat** | Flat iterator | `for x in arr.flat:` |

## Basic indexing and slicing

In [4]:
arr = np.arange(10)

# access single element
arr[-3] # third from last
arr[5] # 5

#slicing [start:stop:step]
print(arr[2:9:2]) # [2 4 6 8]
print(arr[::-1]) # reverse

[2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [ ]:
arr_slice = arr[:6]
arr_slice[2] = 10

print(arr_slice) # [ 0  1 10  3  4  5]
print(arr) # [ 0  1 10  3  4  5  6  7  8  9]
# orginal array change 
# slicing is on view not in copy

arr_copy = arr[5:8].copy()
arr_copy[0] = 64
print(arr_copy) # [64  6  7]
# arr unchanged

### slicing a 2D array

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2d[0][2])   # 3 (first row, third column)
print(arr2d[0, 2])   # 3
print(arr2d[-1, -1]) # 9 (last row, last column)

# access entire row
print(arr2d[1, 0:2]) # [4 5]
print(arr2d[:2])     # first two rows
print(arr2d[:2, 2])  # first two rows, third column
print(arr2d[:, 1:])  # all rows, columns from 1 to end

# replace array
arr2d[1] = [10, 11, 12]  # replace entire row
arr2d[:2, 1:] = 0

### slicing a 3D array

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

print(arr3d.shape)  # (2, 2, 3)

# Access specific element
print(arr3d[0, 1, 2])  # 6 (first group, second row, third column)

# assign to slice 
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)
# [[[42 42 42]
#   [42 42 42]]
# 
#  [[ 7  8  9]
#   [10 11 12]]]

# Restore
arr3d[0] = old_values

### Boolean Indexing

In [30]:
numbers = np.array([[1, 1, 2], [1, 2, 3], [5, 12, 9]])
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
arr = np.arange(7)

bool_arr = numbers == 1
# [[ True  True False]
# [ True False False]
# [False False False]]

# Comparison is vectorized
print(numbers > 5)  # boolean array of same shape

# multiple conditions
print(numbers != 1)

[[False False False]
 [False False False]
 [False  True  True]]
[[False False  True]
 [False  True  True]
 [ True  True  True]]


### select array

In [ ]:
# Boolean array length == number of rows in target array

print(arr[names == 'Bob']) # [0 3]
print(data[names == 'Bob', 2:])
# [[ 1.42623833  1.20256251]
# [ 0.47259961 -0.73949212]]

In [ ]:
# Multiple conditions
mask = (names == 'Bob') | (names == 'Will')
print(mask)
# [ True False  True  True  True False False]

print(data[mask])
# [[ 0.0929  0.2817  0.769   1.2464]
#  [ 1.3529  0.8864 -2.0016 -0.3718]
#  [ 1.669  -0.4386 -0.5397  0.477 ]
#  [ 3.2489 -1.0212 -0.5771  0.1241]]

# AND condition
mask = (data > 0) & (data < 1)  # values between 0 and 1
print(data[mask])  # all values in that range

# Wrong: dont use "and" , "or"
# mask = (names == 'Bob') and (data > 0)  # Error!

### fancy indexing

In [34]:
arr = np.empty ((8, 4))

# # Fill with row indices
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [35]:
# Order is preserved
# You can repeat indices
# Negative indices work

selected = arr[[4, 4, 0, -1, 6]]
selected

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [7., 7., 7., 7.],
       [6., 6., 6., 6.]])

In [37]:
arr = np.arange(32).reshape((8, 4))

result = arr[[1, 5, 7, 2], [0, 3, 1, 2]]
print(result)  # [ 4 23 29 10]
# (1,0) -> 4
# (5,3) -> 23
# (7,1) -> 29
# (2,2) -> 10

[ 4 23 29 10]


### Selecting a Rectangular Region


In [38]:
rows = [1, 5, 7, 2]
cols = [0, 3, 1, 2]

arr[rows][:, cols]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [39]:
# better way
arr[np.ix_(rows, cols)]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### View vs Copy

In [ ]:
arr = np.arange(16).reshape((4,4))

slice_part = arr[:2, :2]
slice_part[0, 0] = 999

# Original array changes
# Because slicing does NOT copy data.
arr

array([[999,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [ ]:
arr = np.arange(16).reshape((4,4))

fancy_part = arr[[0, 1]]
fancy_part[0, 0] = 999

#Original array does NOT change
#Because fancy indexing makes a copy.
arr

| Method | Returns |
|--------|---------|
| **: slicing** | **View** |
| **[list] fancy indexing** | **Copy** |
| **Boolean indexing** | **Copy** |

### Transposing Arrays and Swapping Axes

In [44]:
# Transpose in 2D Arrays
# For 2D arrays, transpose swaps rows and columns.
arr = np.arange(15).reshape((3, 5))
arr.T.shape

(5, 3)

In [45]:
# or
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
# Transpose in Matrix Multiplication

arr = np.arange(18).reshape((6, 3))
result = np.dot(arr.T, arr)

# or using @ operator
result2 = arr.T @ arr

array([[495, 540, 585],
       [540, 591, 642],
       [585, 642, 699]])

In [48]:
# Transpose in Higher Dimensions
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr_transposed = arr.transpose((1, 0, 2))
arr_transposed.shape  # (2, 2, 4)

# Meaning of (1, 0, 2):
# Old axis 1 → new axis 0
# Old axis 0 → new axis 1
# Old axis 2 → stays axis 2

(2, 2, 4)

In [ ]:
# swapaxes (Swap Only Two Axes)
arr = np.arange(16).reshape((2, 2, 4))

# Swap axis 0 and 1
swapped = arr.swapaxes(0, 1)
swapped.shape  # (2, 2, 4)

# Swap axis 1 and 2
swapped2 = arr.swapaxes(1, 2)
swapped2.shape  # (2, 4, 2)

# swapaxes(a, b) only swaps two axes
# transpose() can reorder all axes
# Transpose and swapaxes do NOT copy data.

| Operation          | What it Does            |
| ------------------ | ----------------------- |
| `.T`               | Transpose 2D array      |
| `transpose(order)` | Reorder axes            |
| `swapaxes(a, b)`   | Swap two axes           |
| Memory behavior    | Returns view (not copy) |


| Operation | Behavior | Description |
|-----------|----------|-------------|
| **Slicing** | **view** | Does NOT copy (returns a view) |
| **Fancy indexing** | **copy** | Creates a copy |
| **Boolean indexing** | **copy** | Creates a copy |
| **transpose/swapaxes** | **view** | Does NOT copy |

### Important Notes:
- **Indexing starts from 0**
- **stop in slicing is exclusive** (not included)