# **NumPy**

In [2]:
import numpy as np

## Creating ndarrays

In [ ]:
# 1D array from list
data1 = [6, 7.5, 8, 10]
arr1 = np.array(data1)
print(type(arr1))    # <class 'numpy.ndarray'>
print(arr1.dtype)    # float64 (automatically inferred)

# 2D array from list of list
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2.ndim)     # 2 (dimensions)
print(arr2.shape)    # (2, 4) (rows, columns)
print(arr2.dtype)    # int64

In [ ]:
# zero array
zeros_arr = np.zeros(10) # [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
zeros_2d = np.zeros((3,2))

one_arr = np.ones((3, 2))
empty_arr = np.empty((2, 3)) # random array
# Never assume empty gives zeros!

full_arr = np.full((3, 2), 7)

# eye - (identity)
identity = np.eye(4)

## arange 

In [ ]:
# arange - NumPy version of range
arr = np.arange(10)
print(arr)  # [0 1 2 3 4 5 6 7 8 9]

arr = np.arange(5, 15)  # start, stop
print(arr)  # [5 6 7 8 9 10 11 12 13 14]

arr = np.arange(0, 20, 2)  # start, stop, step
print(arr)  # [0 2 4 6 8 10 12 14 16 18]

arr = np.arange(10, 0, -1)  # negative step
print(arr)  # [10 9 8 7 6 5 4 3 2 1]

## linspace 

In [ ]:
# linspace - equally spaced numbers
# 5 numbers between 0 and 1
arr = np.linspace(0, 1, 5)
print(arr)  # [0.   0.25 0.5  0.75 1.  ]

# 10 numbers between 0 and 2π
angles = np.linspace(0, 2*np.pi, 10)
print(angles)

## random array

In [ ]:
# Random numbers
# Uniform distribution [0, 1)
rand_arr = np.random.rand(3, 4)  # 3x4 array
print(rand_arr)

# Normal distribution (mean=0, std=1)
randn_arr = np.random.randn(3, 4)
print(randn_arr)

# Random integers
randint_arr = np.random.randint(0, 10, size=(3, 4))  # 0 to 9
print(randint_arr)

# Random seed for reproducibility
np.random.seed(42)  # Same random numbers every time
arr1 = np.random.rand(3)
print(arr1)

np.random.seed(42)  # Reset seed
arr2 = np.random.rand(3)
print(arr2)  # Same as arr1!

# otheer way to reset seed
rng = np.random.default_rng(42)
rng.random(3)

| Function | Description | Example |
|----------|-------------|---------|
| **array()** | Create from list/tuple | `np.array([1,2,3])` |
| **zeros()** | All zeros | `np.zeros((3,4))` |
| **ones()** | All ones | `np.ones((2,3))` |
| **empty()** | Uninitialized values | `np.empty((2,2))` |
| **full()** | Constant value | `np.full((3,3), 7)` |
| **arange()** | Similar to range | `np.arange(5,10)` |
| **linspace()** | Equal spacing | `np.linspace(0,1,5)` |
| **eye()** | Identity matrix | `np.eye(4)` |
| **random.rand()** | Uniform random | `np.random.rand(3,3)` |
| **random.randn()** | Normal random | `np.random.randn(3,3)` |

##  Arithmetic with NumPy Arrays

In [ ]:
# From the book example
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# [[1 2 3]
#  [4 5 6]]

# Multiplication
print(arr * arr)
# [[ 1  4  9]
#  [16 25 36]]

# Subtraction
print(arr - arr)
# [[0 0 0]
#  [0 0 0]]

# Division
print(1 / arr)
# [[1.         0.5        0.33333333]
#  [0.25       0.2        0.16666667]]

# Power
print(arr ** 2)
# [[ 1  4  9]
#  [16 25 36]]

# Square root
print(np.sqrt(arr))
# [[1.         1.41421356 1.73205081]
#  [2.         2.23606798 2.44948974]]

In [ ]:
# Scalar operations propagate
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Add scalar
print(arr + 10)
# [[11 12 13]
#  [14 15 16]]

# Multiply by scalar
print(arr * 2)
# [[ 2  4  6]
#  [ 8 10 12]]

# Comparison with scalar
print(arr > 3)
# [[False False False]
#  [ True  True  True]]

# Different operations
print(arr + 1.5)
# [[2.5 3.5 4.5]
#  [5.5 6.5 7.5]]

## ufunc (universal function)

In [ ]:
# From the book - unary ufuncs
arr = np.arange(10)
print(arr)  # [0 1 2 3 4 5 6 7 8 9]

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Binary ufuncs
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)

# Element-wise maximum
print(np.maximum(x, y))

# modf - fractional and integer parts
arr = np.random.randn(7) * 5
remainder, whole = np.modf(arr)
print(whole)
print(remainder)